import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./_components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Desktop / Tablet */}
        <div className="hidden md:flex min-h-screen">
          <Sidebar />
          <main className="flex-1">{children}</main>
        </div>

        {/* Mobile fallback */}
        <div className="md:hidden min-h-screen flex items-center justify-center p-6 text-center">
          <div className="max-w-sm">
            <h1 className="text-2xl font-semibold mb-2">
              Not available on mobile
            </h1>
            <p className="text-muted-foreground">
              Please use a tablet or desktop device to access this dashboard.
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}
